---

-  hosts: all
   become: true
   tasks:

   - name: update repository index
     apt:
       update_cache: yes

   - name: install mpi4py pakage
     apt:
       name: mpi4py
       state: latest

