
---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
 
  - name: Install python package
    apt:
      name: mpich 
      name: python3-pip
      state: latest

  - name: Install mpi4py
    apt:
      name: python3-mpi4py
      state: latest
